# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20171122_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productinorder',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
